project:
  type: website

lang: en-US

date: last-modified

website:
  title: "SAF Business Layer"
  search: true
  sidebar:
    style: docked
    contents:
      - index.qmd
      - SAF-Business-Layer.qmd
      - section: "Primary value streams"
        contents:
          - VS-01.0-Data-Acquisition-and-Ingestion.qmd
          - VS-02.0-Data-Standardization-and-Integration.qmd
          - VS-03.0-Data-Editing-and-Enrichment.qmd
          - VS-04.0-Estimation-Analysis-and-Statistical-Modeling.qmd
          - VS-05.0-Statistical-Product-Composition.qmd
          - VS-06.0-Dissemination-and-Service-Delivery.qmd
      - section: "Supporting value streams"
        contents:
          - VS-07.0-Governance-and-Compliance.qmd
          - VS-08.0-Innovation-and-Methodological-Development.qmd
          - VS-09.0-Infrastructure-and-Platform-Enablement.qmd
          - VS-10.0-Customer-and-Stakeholder-Engagement.qmd

format:
  html:
    toc: true
    number-sections: true
