<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>VS-10 Customer and Stakeholder Engagement – Statistical Architecture Framework</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../framework/vs-09.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4b8eba7d388032a8ef35e180b04aa314.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Statistical Architecture Framework</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../SAF-in-Brief.html"> 
<span class="menu-text">SAF in Brief</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../SAF-Getting-Started.html"> 
<span class="menu-text">Getting Started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../framework/index.html" aria-current="page"> 
<span class="menu-text">Framework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../glossary.html"> 
<span class="menu-text">Glossary</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../open-source.html"> 
<span class="menu-text">Open Source</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../framework/vs-07.html">Supporting value streams</a></li><li class="breadcrumb-item"><a href="../framework/vs-10.html">VS-10 Customer and Stakeholder Engagement</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SAF Architecture Framework</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction and Scope</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/motivation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Motivation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/strategy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Strategy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Business architecture</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/business-architecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Business Architecture</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Production value streams</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-01 Data Acquisition and Ingestion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-02 Data Standardization and Integration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-03 Data Editing and Enrichment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-04 Estimation, Analysis, and Statistical Modeling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-05 Statistical Product Composition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-06 Dissemination and Service Delivery</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Supporting value streams</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-07 Governance and Compliance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-08 Innovation and Methodological Development</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-09.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">VS-09 Infrastructure and Platform Enablement</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../framework/vs-10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">VS-10 Customer and Stakeholder Engagement</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#vs-10.0-customer-and-stakeholder-engagement" id="toc-vs-10.0-customer-and-stakeholder-engagement" class="nav-link active" data-scroll-target="#vs-10.0-customer-and-stakeholder-engagement">VS-10.0 Customer and Stakeholder Engagement</a>
  <ul class="collapse">
  <li><a href="#purpose-and-scope" id="toc-purpose-and-scope" class="nav-link" data-scroll-target="#purpose-and-scope">Purpose and Scope</a></li>
  <li><a href="#position-a-supporting-stream-that-works-across-the-whole-chain" id="toc-position-a-supporting-stream-that-works-across-the-whole-chain" class="nav-link" data-scroll-target="#position-a-supporting-stream-that-works-across-the-whole-chain">Position — a supporting stream that works across the whole chain</a></li>
  <li><a href="#how-it-interacts-with-the-production-chain" id="toc-how-it-interacts-with-the-production-chain" class="nav-link" data-scroll-target="#how-it-interacts-with-the-production-chain">How It Interacts with the Production Chain</a></li>
  <li><a href="#framework-alignment-gamso" id="toc-framework-alignment-gamso" class="nav-link" data-scroll-target="#framework-alignment-gamso">Framework Alignment (GAMSO)</a></li>
  <li><a href="#principles-emphasised" id="toc-principles-emphasised" class="nav-link" data-scroll-target="#principles-emphasised">Principles Emphasised</a></li>
  </ul></li>
  <li><a href="#roles-and-actors" id="toc-roles-and-actors" class="nav-link" data-scroll-target="#roles-and-actors">Roles and Actors</a></li>
  <li><a href="#the-value-stream-flow" id="toc-the-value-stream-flow" class="nav-link" data-scroll-target="#the-value-stream-flow">The Value-Stream Flow</a></li>
  <li><a href="#capability-governance" id="toc-capability-governance" class="nav-link" data-scroll-target="#capability-governance">Capability Governance</a>
  <ul class="collapse">
  <li><a href="#key-performance-indicators" id="toc-key-performance-indicators" class="nav-link" data-scroll-target="#key-performance-indicators">Key Performance Indicators</a></li>
  </ul></li>
  <li><a href="#interactions-services-and-events" id="toc-interactions-services-and-events" class="nav-link" data-scroll-target="#interactions-services-and-events">Interactions, Services and Events</a></li>
  <li><a href="#business-objects-artefacts" id="toc-business-objects-artefacts" class="nav-link" data-scroll-target="#business-objects-artefacts">Business Objects / Artefacts</a></li>
  <li><a href="#applying-this-to-your-nso" id="toc-applying-this-to-your-nso" class="nav-link" data-scroll-target="#applying-this-to-your-nso">Applying This to Your NSO</a>
  <ul class="collapse">
  <li><a href="#maturity-assessment-checklist" id="toc-maturity-assessment-checklist" class="nav-link" data-scroll-target="#maturity-assessment-checklist">Maturity Assessment Checklist</a></li>
  <li><a href="#scenarios" id="toc-scenarios" class="nav-link" data-scroll-target="#scenarios">Scenarios</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="vs-10.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../framework/vs-07.html">Supporting value streams</a></li><li class="breadcrumb-item"><a href="../framework/vs-10.html">VS-10 Customer and Stakeholder Engagement</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">VS-10 Customer and Stakeholder Engagement</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="vs-10.0-customer-and-stakeholder-engagement" class="level2">
<h2 class="anchored" data-anchor-id="vs-10.0-customer-and-stakeholder-engagement">VS-10.0 Customer and Stakeholder Engagement</h2>
<section id="purpose-and-scope" class="level3">
<h3 class="anchored" data-anchor-id="purpose-and-scope">Purpose and Scope</h3>
<p>VS-10.0 ensures the statistical organization remains connected, relevant, and responsive to the needs of those it serves. It builds and maintains mutual understanding and trust between the NSO and its users, data providers, partners, and policy stakeholders. Because official statistics exist to create <strong>public value</strong>, the organization must understand what stakeholders need, communicate transparently, and keep products, services, and policies aligned with real-world demand. It is <strong>not a one-way process</strong> — it is a continuous dialogue that turns stakeholder insight into better products, improved services, and stronger relationships. The value it creates is <strong>relevance and public value</strong>.</p>
<p><em>A note on numbering:</em> each <code>VS-0x.y</code> below is both a value stream stage (<em>what value</em> is added) and a business process (<em>how</em> it is done); the numbering maps one-to-one. See the key-concepts box above.</p>
</section>
<section id="position-a-supporting-stream-that-works-across-the-whole-chain" class="level3">
<h3 class="anchored" data-anchor-id="position-a-supporting-stream-that-works-across-the-whole-chain">Position — a supporting stream that works across the whole chain</h3>
<p>VS-10 is not a stage in the production line. It sits at the <strong>edges</strong> of the chain — facing both the data providers who feed VS-01 and the users who consume VS-06 — and channels what it learns inward to shape the whole chain.</p>
<div class="cell" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-1">flowchart TD
    PROV["Data providers"] --&gt; VS01["VS-01"]
    subgraph primary["Primary Value Streams"]
        direction LR
        VS01 --&gt; VS02["VS-02"] --&gt; VS03["VS-03"] --&gt; VS04["VS-04"] --&gt; VS05["VS-05"] --&gt; VS06["VS-06"]
    end
    VS06 --&gt; USERS["Users &amp; Society"]

    VS10["**VS-10.0 Customer &amp;&lt;br/&gt;Stakeholder Engagement**"]:::hi
    VS10 &lt;--&gt;|"needs &amp; relationships"| PROV
    VS10 &lt;--&gt;|"needs, feedback,&lt;br/&gt;satisfaction"| USERS
    VS10 --&gt;|"needs routed into&lt;br/&gt;design &amp; innovation"| primary

    classDef hi fill:#7c3aed,color:#fff,stroke:#6d28d9,stroke-width:2px
    style PROV fill:#0f766e,color:#fff,stroke:#0f766e
    style USERS fill:#0f766e,color:#fff,stroke:#0f766e
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: VS-10 engages providers and users two-way and channels their needs into the chain.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="How a supporting value stream differs from a primary one">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>How a supporting value stream differs from a primary one
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>No steady-state data transition.</strong> VS-10 does not move data along the chain; it moves <strong>understanding</strong> — needs in, communication and services out.</li>
<li><strong>It runs continuously</strong> as an ongoing dialogue, not per production cycle.</li>
<li><strong>Its output is an enabling capability, not a data artefact:</strong> understood needs, a managed service portfolio, relationships, and impact insight.</li>
<li><strong>It aligns to GAMSO Strategy &amp; Leadership and Corporate Support</strong>, not to GSBPM production phases.</li>
</ul>
</div>
</div>
</section>
<section id="how-it-interacts-with-the-production-chain" class="level3">
<h3 class="anchored" data-anchor-id="how-it-interacts-with-the-production-chain">How It Interacts with the Production Chain</h3>
<p>VS-10 is the chain’s two-way interface with the outside world. It is tightly coupled with <strong>VS-01</strong> (the data providers it engages) and <strong>VS-06</strong> (the users whose feedback it gathers, receiving VS-06.5’s usage and satisfaction data). It translates what it hears into requirements that flow into design across the primary streams and into the <strong>VS-08</strong> innovation backlog.</p>
<div class="cell" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-2">flowchart LR
    EXT["Users, providers,&lt;br/&gt;partners, policymakers"] &lt;--&gt;|"dialogue"| VS10["VS-10&lt;br/&gt;Engagement"]:::hi
    VS06["VS-06 Dissemination"] --&gt;|"usage &amp; feedback (§6.5)"| VS10
    VS10 --&gt;|"user needs &amp; service requirements"| DES["Design across VS-01…06"]
    VS10 --&gt;|"user-driven innovation needs"| VS08["VS-08 Innovation"]

    classDef hi fill:#7c3aed,color:#fff,stroke:#6d28d9
    style EXT fill:#0f766e,color:#fff,stroke:#0f766e
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Interaction with the chain: needs and feedback in; communication, services, and requirements out.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="framework-alignment-gamso" class="level3">
<h3 class="anchored" data-anchor-id="framework-alignment-gamso">Framework Alignment (GAMSO)</h3>
<p>Where the primary streams map to <strong>GSBPM</strong> production phases, VS-10 maps to <strong>GAMSO</strong> leadership and support activities:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>GAMSO area</th>
<th>Relevance to VS-10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Strategy and Leadership</strong></td>
<td>Manage stakeholder and customer relationships; align the portfolio to strategy</td>
</tr>
<tr class="even">
<td><strong>Corporate Support</strong></td>
<td>Manage communications, marketing, user support, and service management</td>
</tr>
<tr class="odd">
<td><strong>SAF capabilities</strong></td>
<td>Needs inventory (supports statistical design &amp; build); customer/stakeholder management</td>
</tr>
</tbody>
</table>
</section>
<section id="principles-emphasised" class="level3">
<h3 class="anchored" data-anchor-id="principles-emphasised">Principles Emphasised</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Principle</th>
<th>Statement</th>
<th>How VS-10 applies it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SAF-P04</strong></td>
<td>Maximize the benefits for the organization</td>
<td>Keeps the whole chain aligned to real stakeholder value and public benefit</td>
</tr>
<tr class="even">
<td><strong>SAF-P08</strong></td>
<td>Data is shared property</td>
<td>Promotes broad, equitable access and reuse of statistics and services</td>
</tr>
<tr class="odd">
<td><strong>SAF-P02</strong></td>
<td>Active support</td>
<td>Runs user support and service management as actively-managed services</td>
</tr>
<tr class="even">
<td><strong>SAF-P11</strong></td>
<td>Privacy By Design</td>
<td>Engages data providers and users with transparency about how their data is used and protected</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="roles-and-actors" class="level2">
<h2 class="anchored" data-anchor-id="roles-and-actors">Roles and Actors</h2>
<div class="callout callout-style-default callout-note callout-titled" title="Indicative, not prescriptive">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Indicative, not prescriptive
</div>
</div>
<div class="callout-body-container callout-body">
<p>The roles below are indicative, not a mandated organizational structure. The SAF deliberately leaves organization design to each NSO — assign these responsibilities to fit your own size, culture, and operating model.</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Role</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Head of Communication / Engagement</strong></td>
<td>Owns the stakeholder strategy and the external relationship</td>
</tr>
<tr class="even">
<td><strong>User Researcher</strong></td>
<td>Collects and analyzes user needs and satisfaction</td>
</tr>
<tr class="odd">
<td><strong>Service / Product Portfolio Manager</strong></td>
<td>Defines and manages the catalog of services and data products</td>
</tr>
<tr class="even">
<td><strong>Account / Relationship Manager</strong></td>
<td>Manages relationships with key providers, partners, and policy users</td>
</tr>
<tr class="odd">
<td><strong>Service Desk / User Support</strong></td>
<td>Operates day-to-day user support</td>
</tr>
<tr class="even">
<td><strong>Communications / Outreach Officer</strong></td>
<td>Runs outreach, workshops, and knowledge-sharing events</td>
</tr>
<tr class="odd">
<td><strong>Impact Analyst</strong></td>
<td>Measures use, societal impact, and satisfaction</td>
</tr>
</tbody>
</table>
</section>
<section id="the-value-stream-flow" class="level2">
<h2 class="anchored" data-anchor-id="the-value-stream-flow">The Value-Stream Flow</h2>
<p>VS-10’s six business processes form a continuous engagement cycle — <strong>understand → offer → deliver → measure</strong> — that feeds back on itself.</p>
<div class="cell" data-fig-width="6" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-3">flowchart LR
    A["10.1 Identify &amp;&lt;br/&gt;Segment Stakeholders"] --&gt; B["10.2 Collect &amp;&lt;br/&gt;Analyze User Needs"]
    B --&gt; C["10.3 Define &amp; Manage&lt;br/&gt;Service Portfolios"]
    C --&gt; D["10.4 Deliver Services &amp;&lt;br/&gt;Manage Relationships"]
    D --&gt; E["10.5 Engage &amp;&lt;br/&gt;Communicate"]
    E --&gt; F["10.6 Monitor Impact&lt;br/&gt;&amp; Satisfaction"]
    F -.-&gt;|"insight feeds the next cycle"| A

    style A fill:#f5f3ff,stroke:#7c3aed
    style B fill:#f5f3ff,stroke:#7c3aed
    style C fill:#eff6ff,stroke:#2563eb
    style D fill:#ecfdf5,stroke:#059669
    style E fill:#ecfdf5,stroke:#059669
    style F fill:#fef3c7,stroke:#d97706
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The six business processes as a continuous engagement cycle.
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Understand — know who and what.</strong> The cycle begins by <strong>identifying and segmenting stakeholders</strong> (10.1): mapping the ecosystem of users, data providers, partners, and policymakers and understanding their roles and expectations. It then <strong>collects and analyzes user needs</strong> (10.2): gathering feedback, running consultations, and translating stakeholder needs into concrete data or service requirements.</p>
<p><strong>Offer — shape the response.</strong> Those needs shape the <strong>definition and management of service portfolios</strong> (10.3): catalogs of business services and data products that address stakeholder needs and align with strategic goals — the bridge between what users want and what the chain produces.</p>
<p><strong>Deliver — serve and communicate.</strong> Services are put into the hands of users by <strong>delivering services and managing relationships</strong> (10.4): operating customer support, service desks, and account management, and monitoring satisfaction and service performance. Alongside delivery, VS-10 <strong>engages and communicates with stakeholders</strong> (10.5): outreach, workshops, and knowledge-sharing that promote awareness and correct understanding of statistical outputs.</p>
<p><strong>Measure — learn and feed back.</strong> Finally it <strong>monitors impact and satisfaction</strong> (10.6): measuring how data and services are used, assessing societal impact, and feeding insight back into planning and innovation — closing the loop so the next cycle of needs is better understood.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Business process</th>
<th>What it produces</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>VS-10.1 Identify and Segment Stakeholders</td>
<td>Stakeholder map and segments</td>
</tr>
<tr class="even">
<td>VS-10.2 Collect and Analyze User Needs</td>
<td>Needs register / service requirements</td>
</tr>
<tr class="odd">
<td>VS-10.3 Define and Manage Service Portfolios</td>
<td>Service &amp; product portfolio</td>
</tr>
<tr class="even">
<td>VS-10.4 Deliver Services and Manage Relationships</td>
<td>Operating support &amp; managed relationships</td>
</tr>
<tr class="odd">
<td>VS-10.5 Engage and Communicate with Stakeholders</td>
<td>Outreach, communication, awareness</td>
</tr>
<tr class="even">
<td>VS-10.6 Monitor Impact and Satisfaction</td>
<td>Impact &amp; satisfaction insight (fed back to the chain)</td>
</tr>
</tbody>
</table>
</section>
<section id="capability-governance" class="level2">
<h2 class="anchored" data-anchor-id="capability-governance">Capability Governance</h2>
<p>VS-10 is itself a capability that is <strong>designed</strong> (engagement strategy, portfolio model), <strong>built</strong> (support and feedback channels — with VS-09), <strong>operated</strong> (continuous dialogue, support, communication), and <strong>improved</strong> (10.6 insight). Unlike a primary stream it produces <strong>relevance, relationships, and insight</strong>, not statistical data, and runs as a <strong>continuous dialogue</strong> rather than a per-cycle production run.</p>
<section id="key-performance-indicators" class="level3">
<h3 class="anchored" data-anchor-id="key-performance-indicators">Key Performance Indicators</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>KPI</th>
<th>Description</th>
<th>Measurement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>User satisfaction</td>
<td>Satisfaction score across user segments and services</td>
<td>Per survey wave, per segment</td>
</tr>
<tr class="even">
<td>Needs conversion</td>
<td>Share of captured needs converted into requirements routed to design or innovation</td>
<td>Per planning period</td>
</tr>
<tr class="odd">
<td>Service performance</td>
<td>Support response and resolution times against the service standard</td>
<td>Monthly</td>
</tr>
<tr class="even">
<td>Reach and engagement</td>
<td>Participation in consultations and outreach; channel reach across segments</td>
<td>Per campaign, annually</td>
</tr>
<tr class="odd">
<td>Impact evidence</td>
<td>Documented uses of official statistics in policy, research, and media</td>
<td>Annually</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="interactions-services-and-events" class="level2">
<h2 class="anchored" data-anchor-id="interactions-services-and-events">Interactions, Services and Events</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Counterpart</th>
<th>VS-10 provides</th>
<th>VS-10 receives</th>
<th>Interaction / event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Users &amp; society</strong></td>
<td>Services, support, communication, the service portfolio</td>
<td>Needs, feedback, satisfaction</td>
<td>“User need captured”, “Consultation”, “Service request”</td>
</tr>
<tr class="even">
<td><strong>Data providers (via VS-01)</strong></td>
<td>Relationship management, transparency</td>
<td>Willingness to provide data, provider needs</td>
<td>“Provider engagement”</td>
</tr>
<tr class="odd">
<td><strong>VS-06 Dissemination</strong></td>
<td>Service requirements &amp; user expectations</td>
<td>Usage and satisfaction data (its §6.5)</td>
<td>“Feedback received”</td>
</tr>
<tr class="even">
<td><strong>VS-08 Innovation &amp; design across VS-01…06</strong></td>
<td>User-driven needs and service requirements</td>
<td>New/improved products and services</td>
<td>“Need routed to design/innovation”</td>
</tr>
</tbody>
</table>
</section>
<section id="business-objects-artefacts" class="level2">
<h2 class="anchored" data-anchor-id="business-objects-artefacts">Business Objects / Artefacts</h2>
<p>VS-10 manages enabling artefacts: the <strong>stakeholder map and segments</strong>, the <strong>user-needs register</strong>, the <strong>service and product portfolio</strong>, <strong>relationship and support records</strong>, and <strong>impact and satisfaction metrics</strong>. These carry user insight into the rest of the chain and are maintained continuously rather than versioned per production cycle. Each artefact nevertheless has a designated owner and a managed lifecycle (SAF-P03): changes are tracked and outdated entries are retired.</p>
</section>
<section id="applying-this-to-your-nso" class="level2">
<h2 class="anchored" data-anchor-id="applying-this-to-your-nso">Applying This to Your NSO</h2>
<section id="maturity-assessment-checklist" class="level3">
<h3 class="anchored" data-anchor-id="maturity-assessment-checklist">Maturity Assessment Checklist</h3>
<ul class="task-list">
<li><label><input type="checkbox">Have we mapped and segmented our stakeholders (users, providers, partners, policymakers)?</label></li>
<li><label><input type="checkbox">Do we systematically collect and analyze user needs and translate them into requirements?</label></li>
<li><label><input type="checkbox">Do we manage a service/product portfolio aligned to those needs and to strategy?</label></li>
<li><label><input type="checkbox">Do we operate user support and manage key relationships, monitoring satisfaction?</label></li>
<li><label><input type="checkbox">Do we measure impact and feed insight back into design and innovation (VS-08)?</label></li>
</ul>
</section>
<section id="scenarios" class="level3">
<h3 class="anchored" data-anchor-id="scenarios">Scenarios</h3>
<p><strong>Scenario A — A new user need becomes a product.</strong> Through consultation (10.2) VS-10 learns that regional policymakers need more granular labour-market data. It logs the requirement, adds a candidate product to the portfolio (10.3), routes the need to design (VS-04/VS-05) and, where new methods are required, to VS-08. Once released by VS-06, VS-10 monitors uptake and satisfaction (10.6) and refines the offering.</p>
<p><strong>Scenario B — Closing the feedback loop.</strong> VS-06.5 reports confusion about confidence intervals in a release. VS-10 analyzes the feedback (10.2/10.6), provides targeted user guidance and a plain-language explainer (10.5), and feeds a documentation improvement back to VS-05/VS-06 design — turning a usability problem into a concrete improvement.</p>
<p><strong>Scenario C — A new audience emerges.</strong> Monitoring shows journalists increasingly republishing statistics from third-party aggregators, sometimes incorrectly. VS-10 identifies data journalists as a distinct segment (10.1), consults them on their needs — machine-readable releases, embeddable visuals, plain-language methodology notes (10.2) — and adds a media-service offer to the portfolio (10.3). The channel requirements are routed to VS-06 and VS-09, an embargoed media briefing service is set up under VS-07’s equal-access policy (10.4/10.5), and citation accuracy in the press is tracked as an impact measure (10.6).</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../framework/vs-09.html" class="pagination-link" aria-label="VS-09 Infrastructure and Platform Enablement">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">VS-09 Infrastructure and Platform Enablement</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>